// Case recipes for the F3 breadth corpus (plan WB-2.3–2.5). Each recipe names a
// clean substrate (catalog/substrates/<name>/) and the textual mutation(s) that
// seed its fault. `catalog/generate-cases.ts` materializes the fixtures from
// these recipes, so the corpus is reproducible rather than hand-copied.
//
// The F2 seed cases (breadth-01..10) are hand-authored and are NOT in this
// file — the recipes cover breadth-11..40 only. Case ids never change once
// assigned (deprecate-don't-renumber).

import type { BugType, DifficultyBand } from './operators.ts';

export interface CaseMutation {
  /** Fixture-relative path under the substrate. */
  readonly file: string;
  /** Exact text present once in the clean substrate file. */
  readonly find: string;
  readonly replace: string;
}

export interface CaseRecipe {
  readonly id: string;
  readonly substrate: string;
  readonly difficulty: DifficultyBand;
  readonly origin: 'operator-catalog' | 'lm-injected' | 'diff-replay' | 'public-bug-canary';
  /** Catalog operator id(s), '+' joined for combined hard faults. */
  readonly operator: string;
  readonly bugType: BugType;
  /** Behaviour-only symptom for the task prompt; never names the mutated line. */
  readonly failureSymptoms: string;
  readonly mutations: readonly CaseMutation[];
  /** Previously-green test titles that flip red on the stored faulted state. */
  readonly f2p: readonly string[];
  /** Test titles that stay green in both states. */
  readonly p2p: readonly string[];
  readonly adequacy: { readonly file: string; readonly delete: string };
  readonly tellAudit: { readonly critic: string; readonly verdict: 'not-told' | 'told'; readonly notes?: string };
  readonly generator: string;
  readonly seed: number;
  readonly engineVersion: string;
  /** Named public reference reproduced (behavior only); canary recipes only. */
  readonly reference?: string;
  /** License/provenance note for `reference`; no code is vendored. */
  readonly license?: string;
}

const NOT_TOLD = 'lane-leader adversarial diff read (tests withheld)' as const;

/** 30 catalog-built cases: 6 substrates × (2 easy + 2 medium + 1 hard). */
export const CASE_RECIPES: readonly CaseRecipe[] = [
  // --- textkit (breadth-11..15) -------------------------------------------
  {
    id: 'breadth-11',
    substrate: 'textkit',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'truncate returns a shortened string even when the text already fits the limit.',
    mutations: [{ file: 'src/truncate.ts', find: 'text.length <= max', replace: 'text.length < max' }],
    f2p: ['returns the text unchanged at the limit'],
    p2p: ['counts words ignoring surrounding whitespace', 'lowercases and hyphen-joins words', 'averages the word lengths'],
    adequacy: { file: 'src/truncate.ts', delete: "return text.length <= max ? text : text.slice(0, max) + '…';" },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A boundary shift; the symptom (text that fits) is not in the diff.' },
    generator: 'catalog:babel:EqualityOperator',
    seed: 111,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-12',
    substrate: 'textkit',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'method-swap',
    bugType: 'function misuse',
    failureSymptoms: 'toKebabCase returns uppercase letters instead of a lowercase slug.',
    mutations: [{ file: 'src/case.ts', find: '.toLowerCase()', replace: '.toUpperCase()' }],
    f2p: ['lowercases and hyphen-joins words'],
    p2p: ['counts words ignoring surrounding whitespace', 'returns the text unchanged at the limit', 'averages the word lengths'],
    adequacy: { file: 'src/case.ts', delete: "return text.trim().toLowerCase().split(/\\s+/).join('-');" },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A case-folding swap; the slug contract lives only in the tests.' },
    generator: 'catalog:babel:MethodExpression',
    seed: 112,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-13',
    substrate: 'textkit',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'arithmetic-swap',
    bugType: 'operator misuse',
    failureSymptoms: 'averageWordLength returns a value far larger than the average word length.',
    mutations: [{ file: 'src/count.ts', find: 'return total / words.length;', replace: 'return total * words.length;' }],
    f2p: ['averages the word lengths'],
    p2p: ['counts words ignoring surrounding whitespace', 'lowercases and hyphen-joins words', 'returns the text unchanged at the limit'],
    adequacy: { file: 'src/count.ts', delete: 'return total / words.length;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A division-to-multiplication swap; the average contract is test-only.' },
    generator: 'catalog:babel:ArithmeticOperator',
    seed: 113,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-14',
    substrate: 'textkit',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'chain-break',
    bugType: 'operator misuse',
    failureSymptoms: 'wordCount counts surrounding whitespace as extra words.',
    mutations: [{ file: 'src/count.ts', find: 'return text.trim().split(/\\s+/).length;', replace: 'return text.split(/\\s+/).length;' }],
    f2p: ['counts words ignoring surrounding whitespace'],
    p2p: ['lowercases and hyphen-joins words', 'returns the text unchanged at the limit', 'averages the word lengths'],
    adequacy: { file: 'src/count.ts', delete: 'return text.trim().split(/\\s+/).length;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A dropped trim in a chain; the whitespace symptom is not in the diff.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-15',
    substrate: 'textkit',
    difficulty: 'hard',
    origin: 'lm-injected',
    operator: 'method-swap+equality-boundary',
    bugType: 'function misuse',
    failureSymptoms: 'toKebabCase returns uppercase letters, and truncate shortens text that already fits the limit.',
    mutations: [
      { file: 'src/case.ts', find: '.toLowerCase()', replace: '.toUpperCase()' },
      { file: 'src/truncate.ts', find: 'text.length <= max', replace: 'text.length < max' },
    ],
    f2p: ['lowercases and hyphen-joins words', 'returns the text unchanged at the limit'],
    p2p: ['counts words ignoring surrounding whitespace', 'averages the word lengths'],
    adequacy: { file: 'src/case.ts', delete: "return text.trim().toLowerCase().split(/\\s+/).join('-');" },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },

  // --- ledger (breadth-16..20) --------------------------------------------
  {
    id: 'breadth-16',
    substrate: 'ledger',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'isOverdrawn reports a zero balance as overdrawn.',
    mutations: [{ file: 'src/balance.ts', find: 'balance < 0', replace: 'balance <= 0' }],
    f2p: ['treats a zero balance as not overdrawn'],
    p2p: ['adds two cent amounts', 'formats cents as a two-decimal amount', 'subtracts the percentage from the amount', 'applies the rate on top of the amount'],
    adequacy: { file: 'src/balance.ts', delete: 'return balance < 0;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A boundary shift; the zero-balance rule is test-only.' },
    generator: 'catalog:babel:EqualityOperator',
    seed: 116,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-17',
    substrate: 'ledger',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'constant-delta',
    bugType: 'value misuse',
    failureSymptoms: 'formatCents divides the amount by the wrong factor.',
    mutations: [{ file: 'src/money.ts', find: '(cents / 100).toFixed(2)', replace: '(cents / 1000).toFixed(2)' }],
    f2p: ['formats cents as a two-decimal amount'],
    p2p: ['adds two cent amounts', 'subtracts the percentage from the amount', 'applies the rate on top of the amount', 'treats a zero balance as not overdrawn'],
    adequacy: { file: 'src/money.ts', delete: 'return (cents / 100).toFixed(2);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A literal change; trivial-prone and easy-tier only.' },
    generator: 'catalog:babel:authored',
    seed: 117,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-18',
    substrate: 'ledger',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'arithmetic-swap',
    bugType: 'operator misuse',
    failureSymptoms: 'applyPercent increases the amount instead of subtracting the percentage.',
    mutations: [{ file: 'src/discount.ts', find: 'return amount - (amount * percent) / 100;', replace: 'return amount + (amount * percent) / 100;' }],
    f2p: ['subtracts the percentage from the amount'],
    p2p: ['adds two cent amounts', 'formats cents as a two-decimal amount', 'applies the rate on top of the amount', 'treats a zero balance as not overdrawn'],
    adequacy: { file: 'src/discount.ts', delete: 'return amount - (amount * percent) / 100;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A sign swap; the discount contract is test-only.' },
    generator: 'catalog:babel:ArithmeticOperator',
    seed: 118,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-19',
    substrate: 'ledger',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'arithmetic-swap',
    bugType: 'operator misuse',
    failureSymptoms: 'withTax subtracts the rate instead of adding it.',
    mutations: [{ file: 'src/discount.ts', find: 'amount * (1 + rate)', replace: 'amount * (1 - rate)' }],
    f2p: ['applies the rate on top of the amount'],
    p2p: ['adds two cent amounts', 'formats cents as a two-decimal amount', 'subtracts the percentage from the amount', 'treats a zero balance as not overdrawn'],
    adequacy: { file: 'src/discount.ts', delete: 'return amount * (1 + rate);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A sign swap; the tax contract is test-only.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-20',
    substrate: 'ledger',
    difficulty: 'hard',
    origin: 'diff-replay',
    operator: 'arithmetic-swap+equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'addCents subtracts instead of adds, and isOverdrawn reports a zero balance as overdrawn.',
    mutations: [
      { file: 'src/money.ts', find: 'return a + b;', replace: 'return a - b;' },
      { file: 'src/balance.ts', find: 'balance < 0', replace: 'balance <= 0' },
    ],
    f2p: ['adds two cent amounts', 'treats a zero balance as not overdrawn'],
    p2p: ['formats cents as a two-decimal amount', 'subtracts the percentage from the amount', 'applies the rate on top of the amount'],
    adequacy: { file: 'src/money.ts', delete: 'return a + b;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'fixture-git-replay',
    seed: 120,
    engineVersion: 'git-history@f3',
  },

  // --- schedule (breadth-21..25) ------------------------------------------
  {
    id: 'breadth-21',
    substrate: 'schedule',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'constant-delta',
    bugType: 'value misuse',
    failureSymptoms: 'isWeekend does not recognise Sunday as a weekend day.',
    mutations: [{ file: 'src/order.ts', find: 'day === 0 || day === 6', replace: 'day === 1 || day === 6' }],
    f2p: ['treats Sunday as a weekend day'],
    p2p: ['measures the minutes between two times', 'formats minutes as hours and minutes', 'does not overlap when one slot ends as the other starts', 'orders slots by start time'],
    adequacy: { file: 'src/order.ts', delete: 'return day === 0 || day === 6;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A literal change; trivial-prone and easy-tier only.' },
    generator: 'catalog:babel:authored',
    seed: 121,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-22',
    substrate: 'schedule',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'constant-delta',
    bugType: 'value misuse',
    failureSymptoms: 'formatDuration reports the wrong hour count.',
    mutations: [{ file: 'src/time.ts', find: 'Math.floor(minutes / 60)', replace: 'Math.floor(minutes / 100)' }],
    f2p: ['formats minutes as hours and minutes'],
    p2p: ['measures the minutes between two times', 'does not overlap when one slot ends as the other starts', 'treats Sunday as a weekend day', 'orders slots by start time'],
    adequacy: { file: 'src/time.ts', delete: 'return `${Math.floor(minutes / 60)}h${minutes % 60}m`;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A literal change; trivial-prone and easy-tier only.' },
    generator: 'catalog:babel:authored',
    seed: 122,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-23',
    substrate: 'schedule',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'logical-swap',
    bugType: 'operator misuse',
    failureSymptoms: 'overlaps reports back-to-back slots as overlapping.',
    mutations: [{ file: 'src/slots.ts', find: 'aStart < bEnd && bStart < aEnd', replace: 'aStart < bEnd || bStart < aEnd' }],
    f2p: ['does not overlap when one slot ends as the other starts'],
    p2p: ['measures the minutes between two times', 'formats minutes as hours and minutes', 'treats Sunday as a weekend day', 'orders slots by start time'],
    adequacy: { file: 'src/slots.ts', delete: 'return aStart < bEnd && bStart < aEnd;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A logical swap; the back-to-back rule is test-only.' },
    generator: 'catalog:babel:LogicalOperator',
    seed: 123,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-24',
    substrate: 'schedule',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'operand-swap',
    bugType: 'variable misuse',
    failureSymptoms: 'sortByStart orders slots from latest to earliest.',
    mutations: [{ file: 'src/order.ts', find: '(a, b) => a - b', replace: '(a, b) => b - a' }],
    f2p: ['orders slots by start time'],
    p2p: ['measures the minutes between two times', 'formats minutes as hours and minutes', 'does not overlap when one slot ends as the other starts', 'treats Sunday as a weekend day'],
    adequacy: { file: 'src/order.ts', delete: 'return [...slots].sort((a, b) => a - b);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An operand swap; the ascending contract is test-only.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-25',
    substrate: 'schedule',
    difficulty: 'hard',
    origin: 'diff-replay',
    operator: 'operand-swap+equality-boundary',
    bugType: 'variable misuse',
    failureSymptoms: 'minutesBetween returns a negative duration, and overlaps reports back-to-back slots as overlapping.',
    mutations: [
      { file: 'src/time.ts', find: 'return end - start;', replace: 'return start - end;' },
      { file: 'src/slots.ts', find: 'aStart < bEnd && bStart < aEnd', replace: 'aStart <= bEnd && bStart <= aEnd' },
    ],
    f2p: ['measures the minutes between two times', 'does not overlap when one slot ends as the other starts'],
    p2p: ['formats minutes as hours and minutes', 'treats Sunday as a weekend day', 'orders slots by start time'],
    adequacy: { file: 'src/time.ts', delete: 'return end - start;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'fixture-git-replay',
    seed: 125,
    engineVersion: 'git-history@f3',
  },

  // --- graph (breadth-26..30) ---------------------------------------------
  {
    id: 'breadth-26',
    substrate: 'graph',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'constant-delta',
    bugType: 'value misuse',
    failureSymptoms: "degree undercounts a node's neighbours by one.",
    mutations: [{ file: 'src/edges.ts', find: '(adj[node] ?? []).length', replace: '(adj[node] ?? []).length - 1' }],
    f2p: ['counts the neighbours of a node'],
    p2p: ['finds a directed edge', 'returns a copy of the neighbour list', 'detects a self-loop among several nodes', 'returns false when the target is unreachable'],
    adequacy: { file: 'src/edges.ts', delete: 'return (adj[node] ?? []).length;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A literal change; trivial-prone and easy-tier only.' },
    generator: 'catalog:babel:authored',
    seed: 126,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-27',
    substrate: 'graph',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'argument-swap',
    bugType: 'variable misuse',
    failureSymptoms: 'hasEdge looks for the wrong endpoint.',
    mutations: [{ file: 'src/edges.ts', find: '(adj[a] ?? []).includes(b)', replace: '(adj[b] ?? []).includes(a)' }],
    f2p: ['finds a directed edge'],
    p2p: ['counts the neighbours of a node', 'returns a copy of the neighbour list', 'detects a self-loop among several nodes', 'returns false when the target is unreachable'],
    adequacy: { file: 'src/edges.ts', delete: 'return (adj[a] ?? []).includes(b);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An argument swap; the edge direction contract is test-only.' },
    generator: 'catalog:babel:authored',
    seed: 127,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-28',
    substrate: 'graph',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'reachable reports an unreachable target as reachable.',
    mutations: [{ file: 'src/bfs.ts', find: 'if (node === target) return true;', replace: 'if (node !== target) return true;' }],
    f2p: ['returns false when the target is unreachable'],
    p2p: ['counts the neighbours of a node', 'finds a directed edge', 'returns a copy of the neighbour list', 'detects a self-loop among several nodes'],
    adequacy: { file: 'src/bfs.ts', delete: 'return false;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An equality flip; the unreachable contract is test-only.' },
    generator: 'catalog:babel:EqualityOperator',
    seed: 128,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-29',
    substrate: 'graph',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'method-swap',
    bugType: 'function misuse',
    failureSymptoms: 'hasSelfLoop only reports a self-loop when every node has one.',
    mutations: [{ file: 'src/paths.ts', find: 'Object.entries(adj).some(', replace: 'Object.entries(adj).every(' }],
    f2p: ['detects a self-loop among several nodes'],
    p2p: ['counts the neighbours of a node', 'finds a directed edge', 'returns a copy of the neighbour list', 'returns false when the target is unreachable'],
    adequacy: { file: 'src/paths.ts', delete: 'return Object.entries(adj).some(([node, next]) => next.includes(node));' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A quantifier swap; the any-vs-all contract is test-only.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-30',
    substrate: 'graph',
    difficulty: 'hard',
    origin: 'diff-replay',
    operator: 'argument-swap+equality-boundary',
    bugType: 'variable misuse',
    failureSymptoms: 'hasEdge looks for the wrong endpoint, and reachable reports an unreachable target as reachable.',
    mutations: [
      { file: 'src/edges.ts', find: '(adj[a] ?? []).includes(b)', replace: '(adj[b] ?? []).includes(a)' },
      { file: 'src/bfs.ts', find: 'if (node === target) return true;', replace: 'if (node !== target) return true;' },
    ],
    f2p: ['finds a directed edge', 'returns false when the target is unreachable'],
    p2p: ['counts the neighbours of a node', 'returns a copy of the neighbour list', 'detects a self-loop among several nodes'],
    adequacy: { file: 'src/edges.ts', delete: 'return (adj[a] ?? []).includes(b);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'fixture-git-replay',
    seed: 130,
    engineVersion: 'git-history@f3',
  },

  // --- validate (breadth-31..35) ------------------------------------------
  {
    id: 'breadth-31',
    substrate: 'validate',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'method-swap',
    bugType: 'function misuse',
    failureSymptoms: 'clamp pushes a value out of range instead of keeping it inside.',
    mutations: [{ file: 'src/range.ts', find: 'Math.min(', replace: 'Math.max(' }],
    f2p: ['keeps a value inside the range'],
    p2p: ['rejects an address without a dotted domain', 'parses a decimal string as base ten', 'lists the missing fields'],
    adequacy: { file: 'src/range.ts', delete: 'return Math.min(Math.max(value, low), high);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A min/max swap; the clamp contract is test-only.' },
    generator: 'catalog:babel:MethodExpression',
    seed: 131,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-32',
    substrate: 'validate',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'requireFields lists the present fields instead of the missing ones.',
    mutations: [{ file: 'src/required.ts', find: 'obj[field] === undefined', replace: 'obj[field] !== undefined' }],
    f2p: ['lists the missing fields'],
    p2p: ['rejects an address without a dotted domain', 'parses a decimal string as base ten', 'keeps a value inside the range'],
    adequacy: { file: 'src/required.ts', delete: 'return fields.filter((field) => obj[field] === undefined);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An equality flip; the missing-vs-present contract is test-only.' },
    generator: 'catalog:babel:EqualityOperator',
    seed: 132,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-33',
    substrate: 'validate',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'radix-coercion-drop',
    bugType: 'value misuse',
    failureSymptoms: 'parseAmount parses a hex-looking string as base sixteen.',
    mutations: [{ file: 'src/number.ts', find: 'parseInt(text, 10)', replace: 'parseInt(text)' }],
    f2p: ['parses a decimal string as base ten'],
    p2p: ['rejects an address without a dotted domain', 'keeps a value inside the range', 'lists the missing fields'],
    adequacy: { file: 'src/number.ts', delete: 'return parseInt(text, 10);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A dropped radix; the base-ten contract is test-only.' },
    generator: 'catalog:ts-morph',
    seed: 133,
    engineVersion: 'ts-morph@28.0.0',
  },
  {
    id: 'breadth-34',
    substrate: 'validate',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'argument-swap',
    bugType: 'variable misuse',
    failureSymptoms: 'clamp swaps the bounds, pushing a value out of range.',
    mutations: [{ file: 'src/range.ts', find: 'return Math.min(Math.max(value, low), high);', replace: 'return Math.min(Math.max(value, high), low);' }],
    f2p: ['keeps a value inside the range'],
    p2p: ['rejects an address without a dotted domain', 'parses a decimal string as base ten', 'lists the missing fields'],
    adequacy: { file: 'src/range.ts', delete: 'return Math.min(Math.max(value, low), high);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An argument swap; the bound order contract is test-only.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-35',
    substrate: 'validate',
    difficulty: 'hard',
    origin: 'lm-injected',
    operator: 'equality-boundary+radix-coercion-drop',
    bugType: 'operator misuse',
    failureSymptoms: 'requireFields lists the present fields instead of the missing ones, and parseAmount parses a hex-looking string as base sixteen.',
    mutations: [
      { file: 'src/required.ts', find: 'obj[field] === undefined', replace: 'obj[field] !== undefined' },
      { file: 'src/number.ts', find: 'parseInt(text, 10)', replace: 'parseInt(text)' },
    ],
    f2p: ['lists the missing fields', 'parses a decimal string as base ten'],
    p2p: ['rejects an address without a dotted domain', 'keeps a value inside the range'],
    adequacy: { file: 'src/required.ts', delete: 'return fields.filter((field) => obj[field] === undefined);' },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },

  // --- queue (breadth-36..40) ---------------------------------------------
  {
    id: 'breadth-36',
    substrate: 'queue',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'equality-boundary',
    bugType: 'operator misuse',
    failureSymptoms: 'shouldRetry retries once past the attempt limit.',
    mutations: [{ file: 'src/retry.ts', find: 'return attempt < max;', replace: 'return attempt <= max;' }],
    f2p: ['stops retrying at the attempt limit'],
    p2p: ['appends a value to the queue', 'returns the first value', 'advances a queued task to running', 'reports the fraction of successes'],
    adequacy: { file: 'src/retry.ts', delete: 'return attempt < max;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A boundary shift; the limit contract is test-only.' },
    generator: 'catalog:babel:EqualityOperator',
    seed: 136,
    engineVersion: '@stryker-mutator/instrumenter@10.0.0',
  },
  {
    id: 'breadth-37',
    substrate: 'queue',
    difficulty: 'easy',
    origin: 'operator-catalog',
    operator: 'constant-delta',
    bugType: 'value misuse',
    failureSymptoms: 'nextState leaves a queued task queued instead of advancing it.',
    mutations: [{ file: 'src/retry.ts', find: "if (state === 'queued') return 'running';", replace: "if (state === 'pending') return 'running';" }],
    f2p: ['advances a queued task to running'],
    p2p: ['appends a value to the queue', 'returns the first value', 'stops retrying at the attempt limit', 'reports the fraction of successes'],
    adequacy: { file: 'src/retry.ts', delete: "if (state === 'queued') return 'running';" },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A literal change; trivial-prone and easy-tier only.' },
    generator: 'catalog:babel:authored',
    seed: 137,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-38',
    substrate: 'queue',
    difficulty: 'medium',
    origin: 'operator-catalog',
    operator: 'chain-break',
    bugType: 'operator misuse',
    failureSymptoms: 'successRate always reports one, ignoring failures.',
    mutations: [{ file: 'src/stats.ts', find: 'events.filter(Boolean).length / events.length', replace: 'events.length / events.length' }],
    f2p: ['reports the fraction of successes'],
    p2p: ['appends a value to the queue', 'returns the first value', 'advances a queued task to running', 'stops retrying at the attempt limit'],
    adequacy: { file: 'src/stats.ts', delete: 'return events.filter(Boolean).length / events.length;' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'A dropped filter in a chain; the success-fraction contract is test-only.' },
    generator: 'catalog:babel:authored',
    seed: 138,
    engineVersion: '@babel/parser@8.0.6',
  },
  {
    id: 'breadth-39',
    substrate: 'queue',
    difficulty: 'medium',
    origin: 'lm-injected',
    operator: 'operand-swap',
    bugType: 'variable misuse',
    failureSymptoms: 'enqueue puts the new value at the front of the queue.',
    mutations: [{ file: 'src/queue.ts', find: 'return [...items, value];', replace: 'return [value, ...items];' }],
    f2p: ['appends a value to the queue'],
    p2p: ['returns the first value', 'advances a queued task to running', 'stops retrying at the attempt limit', 'reports the fraction of successes'],
    adequacy: { file: 'src/queue.ts', delete: 'return [...items, value];' },
    tellAudit: { critic: NOT_TOLD, verdict: 'not-told', notes: 'An operand swap; the FIFO contract is test-only.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
  {
    id: 'breadth-40',
    substrate: 'queue',
    difficulty: 'hard',
    origin: 'lm-injected',
    operator: 'operand-swap+equality-boundary',
    bugType: 'variable misuse',
    failureSymptoms: 'enqueue puts the new value at the front of the queue, and shouldRetry retries once past the attempt limit.',
    mutations: [
      { file: 'src/queue.ts', find: 'return [...items, value];', replace: 'return [value, ...items];' },
      { file: 'src/retry.ts', find: 'return attempt < max;', replace: 'return attempt <= max;' },
    ],
    f2p: ['appends a value to the queue', 'stops retrying at the attempt limit'],
    p2p: ['returns the first value', 'advances a queued task to running', 'reports the fraction of successes'],
    adequacy: { file: 'src/queue.ts', delete: 'return [...items, value];' },
    tellAudit: { critic: NOT_TOLD, verdict: 'told', notes: 'Both diffs are one-token; hard tier is carried by finding two independent faults.' },
    generator: 'lane-leader-lm',
    seed: 0,
    engineVersion: 'lm',
  },
];
