import type { InvocationIdentity, ObservedDriver } from './observation.ts';
import { runSuite, type RunSuiteOptions, type RunSuiteResult } from '../index.ts';
import type { ObservedNativeDriver } from './observed-driver.ts';

export interface NativeConformanceOptions extends Omit<RunSuiteOptions, 'driver'> {
  driver: ObservedNativeDriver;
  expectedCaseIds: string[];
  /** Frozen assignment identity is known before runSuite; invocation UUIDs are generated by runSuite. */
  expectedInvocations: Array<Pick<InvocationIdentity, 'assignmentId' | 'stageId' | 'attemptId'>>;
  expectedTransport: string;
}

const TRANSPORT_DRIVER: Readonly<Record<string, string>> = {
  'codex-exec': 'codex-exec',
  'pi-json': 'pi-json',
  'pi-rpc': 'pi-rpc',
  'zcode-acp': 'zcode-acp',
};

/**
 * G1 entrypoint: this calls the actual runSuite path, whose row and table
 * validators remain authoritative. It is deliberately gated on runner-side
 * identity delivery from the S1 integration.
 */
export async function runNativeConformanceSuite(options: NativeConformanceOptions): Promise<RunSuiteResult> {
  const { expectedCaseIds, expectedInvocations, expectedTransport, ...suiteOptions } = options;
  if (expectedCaseIds.length === 0) throw new Error('native conformance requires at least one expected case id');
  if (expectedInvocations.length === 0) throw new Error('native conformance requires at least one frozen expected invocation identity');
  const expectedDriver = TRANSPORT_DRIVER[expectedTransport];
  if (!expectedDriver) throw new Error(`unsupported native transport for runSuite conformance: ${expectedTransport}`);
  const result = await runSuite(suiteOptions);
  if (result.observations.length === 0) throw new Error('runSuite produced no native observations');
  const foundCases = new Set(result.rows.map((row) => row.case));
  const missingCases = expectedCaseIds.filter((caseId) => !foundCases.has(caseId));
  if (missingCases.length) throw new Error(`runSuite did not return native conformance rows for: ${missingCases.join(', ')}`);
  if (result.tables.length === 0) throw new Error('runSuite returned no native conformance comparison table');

  const driver = options.driver as ObservedNativeDriver & ObservedDriver;
  const expectedIdentityKeys = new Set(expectedInvocations.map(identityKey));
  const actual = result.observations.map(({ observation }) => observation);
  const actualIdentityKeys = new Set(actual.map((observation) => identityKey(observation.identity)));
  for (const key of expectedIdentityKeys) {
    if (!actualIdentityKeys.has(key)) throw new Error(`runSuite did not deliver frozen invocation identity ${key}`);
  }
  if (actual.length !== expectedIdentityKeys.size) {
    throw new Error(`runSuite returned ${actual.length} native observations for ${expectedIdentityKeys.size} expected identities`);
  }
  for (const observation of actual) {
    const delivered = await driver.getObservation(observation.identity.invocationId);
    if (!delivered) throw new Error(`native bridge lost invocation ${observation.identity.invocationId}`);
    if (identityKey(delivered.identity) !== identityKey(observation.identity)) {
      throw new Error(`native observation identity mismatch for ${observation.identity.invocationId}`);
    }
    if (delivered.transport !== expectedTransport) throw new Error(`expected ${expectedTransport}, observed ${delivered.transport}`);
  }

  // The row schema carries the validated lane label; the native transport
  // identity remains in the observation envelope. Aggregation must preserve
  // that same lane in its comparison cell.
  for (const row of result.rows) {
    if (row.driver !== expectedDriver) {
      throw new Error(`native row ${row.case} has driver ${row.driver}; expected ${expectedDriver}`);
    }
  }
  const matchingCells = result.tables.flatMap((table) => table.cells)
    .filter((cell) => cell.driver === expectedDriver);
  if (matchingCells.length === 0) throw new Error(`comparison tables lost native driver lane ${expectedDriver}`);
  return result;
}

function identityKey(identity: Pick<InvocationIdentity, 'assignmentId' | 'stageId' | 'attemptId'>): string {
  return `${identity.assignmentId}/${identity.stageId}/${identity.attemptId}`;
}
