// F6 (WB-5.1): the snapshot index. Reads every committed snapshot
// (reports/snapshots/<date>/README.md header + its *.table.json cells) and
// emits reports/snapshots/README.md — the CQ-5 ratchet page: every snapshot's
// toolkit.lock + suite SHA, and per-toolkit-lock-SHA score deltas. The page is
// GENERATED, never hand-edited (`node scripts/snapshot-index.mjs`); `--check`
// fails when the committed page is stale.

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SNAPSHOTS_ROOT = join(REPO_ROOT, 'reports', 'snapshots');
const INDEX_PATH = join(SNAPSHOTS_ROOT, 'README.md');

const HEADER_NOTE =
  '<!-- generated by scripts/snapshot-index.mjs — do not edit by hand; run `node scripts/snapshot-index.mjs` -->';

/** Read `<snapshot>/README.md`, returning the F6 header fields (or nulls). */
function readHeader(snapshotDir) {
  let text;
  try {
    text = readFileSync(join(snapshotDir, 'README.md'), 'utf8');
  } catch {
    return null;
  }
  const field = (name) => {
    const m = new RegExp(`^${name}:\\s*(\\S+)\\s*$`, 'm').exec(text);
    return m === null ? null : m[1];
  };
  return {
    toolkitLock: field('toolkit\\.lock'),
    suiteSha: field('suite-sha'),
    snapshotDate: field('snapshot-date'),
    runId: field('run-id'),
  };
}

/** Every snapshot dir that carries a README, sorted by directory name (the date). */
function snapshotDirs() {
  return readdirSync(SNAPSHOTS_ROOT)
    .filter((name) => {
      const full = join(SNAPSHOTS_ROOT, name);
      return statSync(full).isDirectory() && readHeader(full) !== null;
    })
    .sort();
}

/** All table files below a snapshot dir, repo-relative. */
function tableFiles(snapshotDir) {
  const out = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name.endsWith('.table.json')) out.push(full);
    }
  };
  walk(snapshotDir);
  return out.sort();
}

/** Cells of one snapshot, keyed by the full cell identity (variant included, F6). */
function snapshotCells(snapshotDir) {
  const cells = new Map();
  let tables = 0;
  for (const file of tableFiles(snapshotDir)) {
    tables += 1;
    const doc = JSON.parse(readFileSync(file, 'utf8'));
    for (const cell of doc.cells ?? []) {
      const key = [doc.role, doc.suite, cell.model, cell.driver, cell.variant ?? 'default'].join(' | ');
      cells.set(key, {
        role: doc.role,
        suite: doc.suite,
        model: cell.model,
        driver: cell.driver,
        variant: cell.variant ?? 'default',
        score: cell.score,
        passed: cell.passed,
        total: cell.total,
        scoreCI: cell.scoreCI ?? null,
      });
    }
  }
  return { cells, tables };
}

const f4 = (n) => (typeof n === 'number' ? n.toFixed(4) : 'n/a');
const signed = (n) => `${n >= 0 ? '+' : ''}${n.toFixed(4)}`;

function renderSnapshotTable(rows) {
  const lines = [
    '| Snapshot | toolkit.lock | suite SHA | run | tables | cells |',
    '|---|---|---|---|---|---|',
  ];
  for (const r of rows) {
    lines.push(
      `| ${r.date} | ${r.toolkitLock ?? '(none)'} | ${r.suiteSha ?? '(none)'} | ${r.runId ?? '(none)'} | ${r.tables} | ${r.cells.size} |`,
    );
  }
  return lines.join('\n');
}

function renderDeltas(rows) {
  const sections = [];
  for (let j = 1; j < rows.length; j += 1) {
    const older = rows[j - 1];
    const newer = rows[j];
    if (older.toolkitLock === newer.toolkitLock) continue;
    const keys = [...new Set([...older.cells.keys(), ...newer.cells.keys()])].sort();
    const lines = [
      `### ${older.date} (toolkit.lock ${older.toolkitLock ?? '(none)'}) → ${newer.date} (toolkit.lock ${newer.toolkitLock ?? '(none)'})`,
      '',
      '| Role / suite | model | driver | variant | old score | new score | Δ | old n | new n |',
      '|---|---|---|---|---|---|---|---|---|',
    ];
    for (const key of keys) {
      const a = older.cells.get(key);
      const b = newer.cells.get(key);
      const label = a ?? b;
      if (a === undefined) {
        lines.push(`| ${label.role} / ${label.suite} | ${label.model} | ${label.driver} | ${label.variant} | (absent) | ${f4(b.score)} | (new cell) | 0 | ${b.total} |`);
        continue;
      }
      if (b === undefined) {
        lines.push(`| ${label.role} / ${label.suite} | ${label.model} | ${label.driver} | ${label.variant} | ${f4(a.score)} | (absent) | (removed cell) | ${a.total} | 0 |`);
        continue;
      }
      lines.push(
        `| ${label.role} / ${label.suite} | ${label.model} | ${label.driver} | ${label.variant} | ${f4(a.score)} | ${f4(b.score)} | ${signed(b.score - a.score)} | ${a.total} | ${b.total} |`,
      );
    }
    sections.push(lines.join('\n'));
  }
  if (sections.length === 0) {
    return 'No cross-toolkit.lock deltas yet: every committed snapshot pins the same `toolkit.lock` value (or only one snapshot exists), so CQ-5 has no toolkit-vs-suite attribution to report. The next snapshot whose `toolkit.lock` differs from a predecessor appears here as a per-cell score delta table.';
  }
  return sections.join('\n\n');
}

function generate() {
  const rows = snapshotDirs().map((date) => {
    const dir = join(SNAPSHOTS_ROOT, date);
    const { cells, tables } = snapshotCells(dir);
    const header = readHeader(dir) ?? {};
    return {
      date: header.snapshotDate ?? date,
      toolkitLock: header.toolkitLock ?? null,
      suiteSha: header.suiteSha ?? null,
      runId: header.runId ?? null,
      tables,
      cells,
    };
  });

  const out = [];
  out.push(HEADER_NOTE);
  out.push('');
  out.push('# Snapshot index');
  out.push('');
  out.push(
    'One row per committed snapshot under `reports/snapshots/`. F6 (WB-5.1) requires every snapshot\n' +
      'README to open with a machine-read header recording the pinned `toolkit.lock` value AND the\n' +
      'suite checkout\'s git SHA (`toolkit.lock:` / `suite-sha:` lines). Without both fields a score\n' +
      'change cannot be attributed to a toolkit change vs a suite change (CQ-5), so the header check\n' +
      'in `test/snapshot-index.test.ts` is a hard gate. Regenerate this file with\n' +
      '`node scripts/snapshot-index.mjs`; the same command with `--check` fails when it is stale.',
  );
  out.push('');
  out.push('## Snapshots');
  out.push('');
  out.push(renderSnapshotTable(rows));
  out.push('');
  out.push('## Score deltas by toolkit.lock SHA');
  out.push('');
  out.push(renderDeltas(rows));
  out.push('');
  return out.join('\n');
}

function main(argv) {
  const text = generate();
  if (argv.includes('--check')) {
    let committed = '';
    try {
      committed = readFileSync(INDEX_PATH, 'utf8');
    } catch {
      committed = '';
    }
    if (committed !== text) {
      console.error(
        `snapshot index is stale: ${relative(REPO_ROOT, INDEX_PATH)} does not match the generator output — run \`node scripts/snapshot-index.mjs\``,
      );
      return 1;
    }
    console.log(`snapshot index current (${INDEX_PATH})`);
    return 0;
  }
  writeFileSync(INDEX_PATH, text);
  console.log(`wrote ${INDEX_PATH}`);
  return 0;
}

process.exit(main(process.argv.slice(2)));
